# content_dict = {
#     '00:00-1:00': 'Camera Features- Night Sight, Portrait Mode, Astrophotography mode, Super Res Zoom, top-tier video stabilization',
#     '1:00-2:00': "Battery Details-All-day battery life, efficiency varies based on specific model and usage"
# }


# content_dict = {
#     '0:00-1:47': 'The event starts with an introduction to Apple Park and a focus on the Apple Watch.', 
#     '1:47-2:40': 'The event kicks off with an introduction to Apple Park and a spotlight on the Apple Watch. The much-anticipated Apple Watch Series 9 is revealed, boasting a new S9 SIP (System in Package) that brings substantial enhancements. These include a CPU with an impressive 60% more transistors than its predecessor, Series 8, a GPU that is 30% faster, and the incorporation of a four-core Neural Engine to turbocharge machine learning capabilities.', 
#     '2:40-3:02': 'At Apple Park, Apple introduced the Apple Watch Series 9, powered by the advanced S9 SIP. It features a CPU with 60% more transistors than the Series 8, a 30% faster GPU, and an upgraded four-core Neural Engine for enhanced machine learning. Siri now processes requests directly on the device, increasing speed and security. The Series 9 also offers a 25% improvement in dictation accuracy over its predecessor.', 
#     '3:02-4:17': 'At the Apple event, the Apple Watch Series 9 was unveiled with significant upgrades. It has an S9 SIP with 60% more transistors, a 30% faster GPU, and an enhanced four-core Neural Engine. Siri now processes directly on the watch, improving speed and security. Dictation accuracy is 25% better, and the Series 9 includes a second-gen Ultra Wideband chip and a brighter always-on Retina display.', 
#     '4:17-5:26': "Apple unveiled the Apple Watch Series 9 at their event. This new watch, powered by the S9 SIP, boasts a CPU with 60% more transistors, a 30% faster GPU, and a four-core Neural Engine. Siri now operates directly on the device, with a 25% increase in dictation accuracy. Series 9 features a brighter always-on Retina display, a second-gen Ultra Wideband chip for iPhone tracking, and introduces a 'Double Tap' gesture. Offering diverse color and material choices, it's Apple's first carbon-neutral product.", 
#     '5:26-6:49': "At the Apple event, the Apple Watch Series 9 was unveiled, showcasing upgrades such as the S9 SIP with a CPU having 60% more transistors and a 30% faster GPU. It has an enhanced four-core Neural Engine, on-device Siri processing, and 25% better dictation accuracy. It also features a second-gen Ultra Wideband chip, a brighter always-on Retina display, and the 'Double Tap' gesture. The Series 9 offers varied colors and is Apple's first carbon-neutral product. Additionally, the Apple Watch Ultra 2 was introduced with the Series 9 SIP, a high-brightness display, and night mode.", 
#     '6:49-09:09': "At the Apple event, the Apple Watch Series 9 was unveiled, featuring the new S9 SIP with a CPU having 60% more transistors, a 30% faster GPU, and a four-core Neural Engine. Siri now processes requests on-device, improving speed and security, and dictation accuracy has been boosted by 25%. The Series 9 has a second-gen Ultra Wideband chip, a brighter always-on Retina display, and a new 'Double Tap' gesture. It's also Apple's first carbon-neutral product, available in various colors and materials. The event also highlighted the Apple Watch Ultra 2, with the Series 9 SIP, a high-brightness display, night mode, enhanced battery life, and new band colors.", 
#     '09:09-9:34': "At the Apple event, the Apple Watch Series 9 was introduced, featuring the new S9 SIP. It has a CPU with 60% more transistors, a 30% faster GPU, and a four-core Neural Engine for advanced machine learning. Siri now processes directly on the device, enhancing speed and security. Dictation accuracy is 25% better. The Series 9 includes a second-gen Ultra Wideband chip, a brighter always-on Retina display, and the 'Double Tap' gesture. Available in diverse colors and materials, it's Apple's inaugural carbon-neutral product. The event also debuted the Apple Watch Ultra 2 with the Series 9 SIP, a brighter display, night mode, enhanced battery life, and new band colors. Pricing details for Series 9, Ultra 2, and the Apple Watch SE were also provided.", 
#     '9:34-9:45': "At the Apple event, the Apple Watch Series 9 was unveiled with a new S9 SIP, featuring an enhanced CPU, GPU, and a four-core Neural Engine. Siri processes on-device for better speed and security, and dictation is 25% more accurate. The watch has a brighter display, a 'Double Tap' gesture, and is Apple's first carbon-neutral product. The Apple Watch Ultra 2 was also introduced with improved features and new band colors. Pricing for Series 9, Ultra 2, and the Apple Watch SE was announced.", 
#     '9:45-11:20': "At the Apple event in Apple Park, the Apple Watch Series 9 was launched, boasting the new S9 SIP, on-device Siri processing, 25% improved dictation, a brighter Retina display, and a 'Double Tap' gesture. It's also Apple's first carbon-neutral product. The Apple Watch Ultra 2 was introduced with enhanced features and new band colors. Pricing for the Series 9, Ultra 2, and Apple Watch SE was announced. The iPhone 15, available in two sizes, debuted with a new 'Dynamic Island' design and a brighter Super Retina XDR display, featuring aerospace-grade aluminum and vibrant color-infused glass options.", 
#     '11:20-13:53': "Apple unveiled the Apple Watch Series 9 with the new S9 SIP, boasting a CPU with 60% more transistors, a 30% faster GPU, and a four-core Neural Engine. Siri now processes requests on-device, and the watch features improved dictation, a brighter always-on Retina display, and a 'Double Tap' gesture. The Series 9 is Apple's first carbon-neutral product. The Apple Watch Ultra 2 was also introduced, leveraging the Series 9 SIP, a high-brightness display, and night mode. Additionally, the iPhone 15 was showcased with the new Dynamic Island design, a brighter Super Retina XDR display, a 48-megapixel main camera, and powered by the A16 Bionic chip.",
#     '13:53-16:43': "At the Apple event, the Apple Watch Series 9 was introduced with the S9 SIP, showcasing a 60% transistor-rich CPU, 30% faster GPU, and a four-core Neural Engine. Siri now processes on-device, ensuring faster responses and increased security. The Series 9 watch boasts an improved Retina display, a 'Double Tap' gesture, and is Apple's debut carbon-neutral product. The Apple Watch Ultra 2, with features mirroring the Series 9, was also launched. The iPhone 15 was highlighted, boasting a new design, enhanced Super Retina XDR display, a 48-megapixel camera, the A16 Bionic chip, and innovative features like Ultra Wideband tech and satellite-enabled emergency services.", 
#     '16:43-End': "At the Apple Park event, Apple unveiled the Apple Watch Series 9 with the new S9 SIP, showcasing enhanced performance, on-device Siri processing, improved dictation, and a 'Double Tap' gesture. It also features a brighter Retina display and is Apple's first carbon-neutral watch. The Apple Watch Ultra 2 was introduced, complementing the Series 9 with similar battery improvements and new band colors. The iPhone 15 was revealed with the 'Dynamic Island' design, enhanced Super Retina XDR display, a 48-megapixel camera, A16 Bionic chip, and satellite-based emergency features. Finally, Apple announced USB-C support for iPhone 15 and detailed the iPhone 15 Pro's A17 Pro chip and camera features."
# }

content_dict = {
    # '0:00-1:47': 'The event starts with an introduction to Apple Park and a focus on the Apple Watch.', 
    #'0:00-2:40': 'The event kicks off with an introduction to Apple Park and a spotlight on the Apple Watch. The much-anticipated Apple Watch Series 9 is revealed, boasting a new S9 SIP (System in Package) that brings substantial enhancements. These include a CPU with an impressive 60% more transistors than its predecessor, Series 8, a GPU that is 30% faster, and the incorporation of a four-core Neural Engine to turbocharge machine learning capabilities.', 
    '0:00-0:02': 'At Apple Park, Apple introduced the Apple Watch Series 9, powered by the advanced S9 SIP. It features a CPU with 60% more transistors than the Series 8, a 30% faster GPU, and an upgraded four-core Neural Engine for enhanced machine learning. Siri now processes requests directly on the device, increasing speed and security. The Series 9 also offers a 25% improvement in dictation accuracy over its predecessor.', 
    '0:02-4:17': 'At the Apple event, the Apple Watch Series 9 was unveiled with significant upgrades. It has an S9 SIP with 60% more transistors, a 30% faster GPU, and an enhanced four-core Neural Engine. Siri now processes directly on the watch, improving speed and security. Dictation accuracy is 25% better, and the Series 9 includes a second-gen Ultra Wideband chip and a brighter always-on Retina display.', 
    '4:17-5:26': "Apple unveiled the Apple Watch Series 9 at their event. This new watch, powered by the S9 SIP, boasts a CPU with 60% more transistors, a 30% faster GPU, and a four-core Neural Engine. Siri now operates directly on the device, with a 25% increase in dictation accuracy. Series 9 features a brighter always-on Retina display, a second-gen Ultra Wideband chip for iPhone tracking, and introduces a 'Double Tap' gesture. Offering diverse color and material choices, it's Apple's first carbon-neutral product.", 
    '5:26-6:49': "At the Apple event, the Apple Watch Series 9 was unveiled, showcasing upgrades such as the S9 SIP with a CPU having 60% more transistors and a 30% faster GPU. It has an enhanced four-core Neural Engine, on-device Siri processing, and 25% better dictation accuracy. It also features a second-gen Ultra Wideband chip, a brighter always-on Retina display, and the 'Double Tap' gesture. The Series 9 offers varied colors and is Apple's first carbon-neutral product. Additionally, the Apple Watch Ultra 2 was introduced with the Series 9 SIP, a high-brightness display, and night mode.", 
    '6:49-09:09': "At the Apple event, the Apple Watch Series 9 was unveiled, featuring the new S9 SIP with a CPU having 60% more transistors, a 30% faster GPU, and a four-core Neural Engine. Siri now processes requests on-device, improving speed and security, and dictation accuracy has been boosted by 25%. The Series 9 has a second-gen Ultra Wideband chip, a brighter always-on Retina display, and a new 'Double Tap' gesture. It's also Apple's first carbon-neutral product, available in various colors and materials. The event also highlighted the Apple Watch Ultra 2, with the Series 9 SIP, a high-brightness display, night mode, enhanced battery life, and new band colors.", 
    '09:09-9:34': "At the Apple event, the Apple Watch Series 9 was introduced, featuring the new S9 SIP. It has a CPU with 60% more transistors, a 30% faster GPU, and a four-core Neural Engine for advanced machine learning. Siri now processes directly on the device, enhancing speed and security. Dictation accuracy is 25% better. The Series 9 includes a second-gen Ultra Wideband chip, a brighter always-on Retina display, and the 'Double Tap' gesture. Available in diverse colors and materials, it's Apple's inaugural carbon-neutral product. The event also debuted the Apple Watch Ultra 2 with the Series 9 SIP, a brighter display, night mode, enhanced battery life, and new band colors. Pricing details for Series 9, Ultra 2, and the Apple Watch SE were also provided.", 
    '9:34-9:45': "At the Apple event, the Apple Watch Series 9 was unveiled with a new S9 SIP, featuring an enhanced CPU, GPU, and a four-core Neural Engine. Siri processes on-device for better speed and security, and dictation is 25% more accurate. The watch has a brighter display, a 'Double Tap' gesture, and is Apple's first carbon-neutral product. The Apple Watch Ultra 2 was also introduced with improved features and new band colors. Pricing for Series 9, Ultra 2, and the Apple Watch SE was announced.", 
    '9:45-11:20': "At the Apple event in Apple Park, the Apple Watch Series 9 was launched, boasting the new S9 SIP, on-device Siri processing, 25% improved dictation, a brighter Retina display, and a 'Double Tap' gesture. It's also Apple's first carbon-neutral product. The Apple Watch Ultra 2 was introduced with enhanced features and new band colors. Pricing for the Series 9, Ultra 2, and Apple Watch SE was announced. The iPhone 15, available in two sizes, debuted with a new 'Dynamic Island' design and a brighter Super Retina XDR display, featuring aerospace-grade aluminum and vibrant color-infused glass options.", 
    '11:20-13:53': "Apple unveiled the Apple Watch Series 9 with the new S9 SIP, boasting a CPU with 60% more transistors, a 30% faster GPU, and a four-core Neural Engine. Siri now processes requests on-device, and the watch features improved dictation, a brighter always-on Retina display, and a 'Double Tap' gesture. The Series 9 is Apple's first carbon-neutral product. The Apple Watch Ultra 2 was also introduced, leveraging the Series 9 SIP, a high-brightness display, and night mode. Additionally, the iPhone 15 was showcased with the new Dynamic Island design, a brighter Super Retina XDR display, a 48-megapixel main camera, and powered by the A16 Bionic chip.",
    '13:53-16:43': "At the Apple event, the Apple Watch Series 9 was introduced with the S9 SIP, showcasing a 60% transistor-rich CPU, 30% faster GPU, and a four-core Neural Engine. Siri now processes on-device, ensuring faster responses and increased security. The Series 9 watch boasts an improved Retina display, a 'Double Tap' gesture, and is Apple's debut carbon-neutral product. The Apple Watch Ultra 2, with features mirroring the Series 9, was also launched. The iPhone 15 was highlighted, boasting a new design, enhanced Super Retina XDR display, a 48-megapixel camera, the A16 Bionic chip, and innovative features like Ultra Wideband tech and satellite-enabled emergency services.", 
    '16:43-End': "At the Apple Park event, Apple unveiled the Apple Watch Series 9 with the new S9 SIP, showcasing enhanced performance, on-device Siri processing, improved dictation, and a 'Double Tap' gesture. It also features a brighter Retina display and is Apple's first carbon-neutral watch. The Apple Watch Ultra 2 was introduced, complementing the Series 9 with similar battery improvements and new band colors. The iPhone 15 was revealed with the 'Dynamic Island' design, enhanced Super Retina XDR display, a 48-megapixel camera, A16 Bionic chip, and satellite-based emergency features. Finally, Apple announced USB-C support for iPhone 15 and detailed the iPhone 15 Pro's A17 Pro chip and camera features."
}
